In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
df2['degination']=["eng","doct","police","nurs"]

In [8]:
df2

    Name  Age      City  Salary degination
0   John   28  New York   65000        eng
1   Anna   34     Paris   70000       doct
2  Peter   29    Berlin   62000     police
3  Linda   42    London   85000       nurs

removing columns

In [13]:
df2.drop('degination' , axis=1, inplace=True)

In [ ]:
df2.drop(0 ,  axis=0)

    Name  Age    City  Salary degination
1   Anna   34   Paris   70000       doct
2  Peter   29  Berlin   62000     police
3  Linda   42  London   85000       nurs

In [ ]:
df2.drop('Name',axis=1)

   Age      City  Salary degination
0   28  New York   65000        eng
1   34     Paris   70000       doct
2   29    Berlin   62000     police
3   42    London   85000       nurs

selecting row

In [ ]:
df2

    Name  Age      City  Salary degination
0   John   28  New York   65000        eng
1   Anna   34     Paris   70000       doct
2  Peter   29    Berlin   62000     police
3  Linda   42    London   85000       nurs

In [ ]:
df2.loc[[0,1]]

   Name  Age      City  Salary degination
0  John   28  New York   65000        eng
1  Anna   34     Paris   70000       doct

In [ ]:
df2.loc[[1]]

   Name  Age   City  Salary degination
1  Anna   34  Paris   70000       doct

In [ ]:
df.iloc[2]

Name       Peter
Age           29
City      Berlin
Salary     62000
Name: 2, dtype: object

selecting subset of row and column

In [ ]:
df.loc[[0,1]][['Age','City']]

   Age      City
0   28  New York
1   34     Paris

conditional statement

In [ ]:
df2

    Name  Age      City  Salary degination
0   John   28  New York   65000        eng
1   Anna   34     Paris   70000       doct
2  Peter   29    Berlin   62000     police
3  Linda   42    London   85000       nurs

In [ ]:
df2[df2['Age']<30]

    Name  Age      City  Salary degination
0   John   28  New York   65000        eng
2  Peter   29    Berlin   62000     police

In [ ]:
##I only want to see those people whose age is above 30

In [ ]:
df2[df2['Age']>30]

    Name  Age    City  Salary degination
1   Anna   34   Paris   70000       doct
3  Linda   42  London   85000       nurs

In [ ]:
#I only want poeple whose age is above 30 and their city must be paris

In [ ]:
df2[(df2["Age"]>30)&(df2["City"]=='Paris')]

   Name  Age   City  Salary degination
1  Anna   34  Paris   70000       doct

In [10]:
df2

    Name  Age      City  Salary degination
0   John   28  New York   65000        eng
1   Anna   34     Paris   70000       doct
2  Peter   29    Berlin   62000     police
3  Linda   42    London   85000       nurs