In [39]:
import numpy as np
import pandas as pd

finding mising data

In [40]:

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [41]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [42]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [43]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [44]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [45]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [46]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

Filling missing data

In [47]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [48]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [49]:
values={'A':200,'B':400,'C':344,'D':3434}
df.fillna(value=values,inplace=True)

In [50]:
df

       A  B      C       D
0    1.0  1    1.0     1.0
1    2.0  2    2.0  3434.0
2  200.0  3    3.0  3434.0
3    4.0  4  344.0  3434.0
4    5.0  5  344.0     5.0

In [51]:
df.fillna((df.mean()))

       A  B      C       D
0    1.0  1    1.0     1.0
1    2.0  2    2.0  3434.0
2  200.0  3    3.0  3434.0
3    4.0  4  344.0  3434.0
4    5.0  5  344.0     5.0